### ISSUE TITLE
Create React App.

### ISSUE THREAD

**Issue by MahdiSohaily** [MahdiSohaily/spaceX#1]
- We have created [this](https://github.com/MahdiSohaily/spaceX/projects/3) Kanban board in order to do the react group project task with my teammate @luccamicale.
- We have removed all the activities related to the third teammate because we are just two people in the group, and that is why the number of cards is 17 out of 24.

**Comment by descholar-ceo** [comment]
Hi @MahdiSohaily && @luccamicale 🤝 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 All cards cover the poroject requirement and scope ✔️ 
👍🏽 All participants have shared equally cards ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MahdiSohaily** [comment]
Thanks, dear @descholar-ceo.
